version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: ucl-draw-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    networks:
      - ucl-draw-network
    depends_on:
      - postgres


  nginx:
    image: nginx:latest
    container_name: ucl-draw-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ucl-draw-network

  node:
    image: node:20
    container_name: ucl-draw-node
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "80:5173"
    environment:
      - HOST=0.0.0.0
    networks:
      - ucl-draw-network

  postgres:
    image: postgres:15
    container_name: ucl-draw-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel12
      POSTGRES_DB: ucldrawer_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ucl-draw-network

networks:
  ucl-draw-network:
    driver: bridge

volumes:
  postgres-data:
